var _all_win_tools_but = $("#win_tools_but");
var _all_win_datagrid_main = $("#win_datagrid_main");
var _all_win_datagrid_pg = $("#_all_win_datagrid_pg");

var _all_queryAction = "mdMaterielInfoService.getOperatorsPagerModelObject";

var _all_win_datagrid;
var _all_datagrid_height;
var _off_wmsMiIds; //下架商品ID
var _que_brand = ''; //确定选择的品牌
var _que_applicantname = ''; //确定选择的商家名称
var _que_matName = '';//确定搜索的关键词
var _que_state = '';//确定搜索的商品的状态
var _que_matType = '';//确定选择的分类
var _currentList = [];

var _MainToolbar = {
    toolBarId: "tools_but",
    items: [
        {
            title: "批量下架",
            id: "win_but_search",
            icon: "",
            colourStyle: "default",
            rounded: true,
            clickE: open_Off_Shelf_Goods_Box2
        },
        {
            title: "导出EXCEL",
            id: "win_but_export",
            icon: '',
            colourStyle: "success",
            rounded: true,
            clickE: export_all
        }
    ]
}
//主表
var _DataGrid = {
    cols: [
        {title: '商家商品编号', name: 'matCode', sortable: true, width: 90, align: 'center'},
        {title: '商品图片', name: 'logo', width: 20, align: 'center', renderer: renderLogo},
        {title: '商品名称', name: 'matName', sortable: true, width: 100, align: 'center', renderer: renderMatName},
        {title: '品牌', sortable: true, name: 'brand', width: 10, align: 'center'},
        {title: 'SKU价格', name: 'sku', width: 20, align: 'center', renderer: renderSKU},
        {title: '销量', sortable: true, name: 'number1', width: 10, align: 'center', renderer: renderNum},
        {title: '商品状态', sortable: true, name: 'state', width: 20, align: 'center', renderer: formatState},
        {title: '商家名称', sortable: true, name: 'applicantName', width: 100, align: 'center'},
        {title: '创建时间', sortable: true, name: 'createDate', width: 100, align: 'center'},
        {title: '日志', name: 'log', width: 5, align: 'center', renderer: renderLog},
        {title: '操作', name: 'mddCon', width: 100, align: 'center', renderer: control}
    ]
    , remoteSort: false
    , name: 'materielListGrid'
    , height: 'auto'
    , url: getMMGridUrl()
    , mmPaginatorOpt: _all_win_datagrid_pg
}


//去查看商品详情
function gotoViewGood(wmsMiId) {
    var newTab = window.open('about:blank');
    newTab.location.href = '/dentistmall/xiangxi.htm?wmsMiId=' + wmsMiId;
}

//商品名称
function renderMatName(val, item, rowIndex) {
    let str = '';
    str += '<a onclick="gotoViewGood(' + item.wmsMiId + ')">' + item.matName + '</a>';
    return str;
}

//图标
function renderLogo(val, item, rowIdex) {
    let str = '';
    if (item.lessenFilePath == undefined)
        str = '';
    else
        str += '<img onclick="gotoViewGood(' + item.wmsMiId + ')" src="' + item.lessenFilePath + '" style=\"width: 40px; height: 40px;cursor: pointer\" />';
    return str;
}

// SKU
function renderSKU(val, item, rowIndex) {
    let str = '';
    // str += '<img onclick="viewMaterielNorm(' + item.wmsMiId + ')" style="width: 25px;" src="/dentistmall/img/sku.png" />';
    str += '<img onclick="viewMaterielNorm(\'' + item.matCode + '\',' + item.wmsMiId + ')" style="width: 25px;" src="/dentistmall/img/sku.png" />';
    return str;
}

//打开SKU窗口
function viewMaterielNorm(matCode, wmsMiId) {
    var data = "wmsMiId=" + wmsMiId + '&matCode=' + matCode;
    var att_url = $.supper("getServicePath", {"data": data, url: "/jsp/dentistmall/business/viewGoodSkuInfo.jsp"});
    var tt_win = $.supper("showWin", {
        url: att_url,
        title: "SKU价格",
        icon: "fa-th-list",
        width: 800, height: 600
    });
}

//销量
function renderNum(val, item, rowIdex) {
    let str = '';
    if (item.number1 == undefined || item.number1 == null || item.number1 == '')
        str = '0';
    else
        str = item.number1;
    return str;
}

//上架状态
function formatState(val, item, rowIndex) {
    let str = '';
    if (item.state == 1) {
        str += '<span>已上架</span>';
    } else if (item.state == 2) {
        str += '<span>下架</span>';
    } else if (item.state == 3) {
        str += '<span>违规下架</span>';
    } else {
        str += '';
    }
    return str;
}

// 日志
function renderLog(val, item, rowIndex) {
    let str = '';
    str += '<img onclick="toDetailLog(' + item.wmsMiId + ')" style="width: 25px;" src="/dentistmall/img/format_log.png" />';
    return str;
}

// 查看日志
function toDetailLog(wmsMiId) {
    var data = "wmsMiId=" + wmsMiId;
    var att_url = $.supper("getServicePath", {
        'data': data,
        url: "/jsp/dentistmall/business/vieGoodOperationLog.jsp"
    });
    var tt_win = $.supper("showWin", {
        url: att_url, title: "商品日志", icon: "fa-th-list", width: 800, height: 520
    });
}

//操作
function control(val, item, rowIndex) {
    let str = '';
    str += '<a onclick="gotoViewGood(' + item.wmsMiId + ')" >详情</a>&nbsp;&nbsp;';
    if (item.state == 1) {
        str += '<img onclick="open_Off_Shelf_Goods_Box(' + item.wmsMiId + ')" style="width: 25px;" src="/dentistmall/img/xiajia.png" />';
    }
    return str;
}

//底部全选
function selecAll() {
    $(".checkAll").click()
}

/**
 * 页面初始化函数
 */
$(function () {
    _all_win_tools_but.xtoolbar('create', _MainToolbar);
    _all_datagrid_height = $(window).height() - 46 - 95;
    _DataGrid.height = _all_datagrid_height;
    _all_win_datagrid = _all_win_datagrid_main.xdatagrid('create', _DataGrid);
    main_search();
    initTree();
    //设置按钮图标跟随文字水平居中,按钮长度
    $("#win_but_search").css("width", "110px");
    $("#win_but_search").css("vertical-align", "middle");
    $("#win_but_add").css("width", "110px");
    $("#win_but_add").css("vertical-align", "middle");

    getMdMaterielInfoCount();//获取全部，上架，未上架数量
    getBrandList();//获取品牌列表
    getApplicantNameList();//获取商家列表

    $("#brand").html('请选择品牌');
    $("#applicantName").html('商家名称');

    //品牌弹窗取消选择按钮
    if (_brandnamestr == '') {
        $("#cancelBrandNamesBtn").html('');
    }
    //商家弹窗取消选择按钮
    if (_applicantnamestr == '') {
        $("#cancelApplicantNameBtn").html('');
    }
});

function selectState() {
    _que_state = $("#searchState").val();
}

function hasClass(element, className) {
    const regExp = new RegExp("\\b" + className + "\\b", "gi");
    return regExp.test(element.className);
}

/**
 * 获取数据查询地址
 */
function getMMGridUrl() {
    _que_matName = $("#searchName").val();
    var data = 'matName=' + _que_matName + '&state=' + _que_state + '&brand=' + _que_brand + '&applicantName=' + _que_applicantname + '&matType=' + _que_matType;
    var att_url = $.supper("getServicePath", {"service": _all_queryAction, "data": data});
    return att_url;
}

/**
 * 对主表进行查询（刷新）操作
 */
function main_search() {
    _all_win_datagrid.opts.url = getMMGridUrl();
    _all_win_datagrid.load();
    _all_win_datagrid.on('loadSuccess', function (e, data) {
        _currentList = data.items;
        $(".selectItem").prop("checked", false);
    });
    _all_win_datagrid.on('cellSelected', function (e, item, rowIndex, colIndex) {
        setTimeout(function () {
            var aaa = _all_win_datagrid.selectedRows();
            if (aaa.length == _currentList.length) {
                $(".selectItem").prop("checked", true);
            } else {
                $(".selectItem").prop("checked", false);
            }
        }, 300);
    });
    _all_win_datagrid.$head.find('th .checkAll').on('click', function (e) {
        var aaa = _all_win_datagrid.selectedRows();
        if (aaa.length == _currentList.length) {
            $(".selectItem").prop("checked", true);
        } else {
            $(".selectItem").prop("checked", false);
        }
    });
}

var setting;
var lastExpandNode;

function initTree() {
    //设置树形数据开始
    setting = {
        data: {
            simpleData: {
                enable: true,
                idKey: "id",
                pIdKey: "pId",
                isParent: "isParent"
            }
        },
        async: {
            enable: true,
            url: $.supper("getServicePath", {"service": "MdMaterielTypeService.getTreeListByMdMmtId"}),  //获取异步数据的地址
            autoParam: ["id"],
            dataFilter: filter //设置数据的展现形式
        },
        callback: {//增加点击事件
            beforeClick: function (treeId, treeNode) {
                if (treeNode.id > 0) {
                    $("#matType").val("/" + treeNode.id + "/");
                    _que_matType = treeNode.id;
                    main_search();
                } else {
                    $("#matType").val("");
                    _que_matType = '';
                    main_search();
                }

            }
        }
    };
    var zNodes = [{id: 0, pId: "", name: "商品类别列表", isParent: true}];
    $.fn.zTree.init($("#tree"), setting, zNodes);
    //自动展现第一层树
    var zTree = $.fn.zTree.getZTreeObj("tree");
    var node = zTree.getNodesByParam("id", "0");
    lastExpandNode = node;
    zTree.expandNode(node[0], true, false, false);

}

//设置数据的展现形式
function filter(treeId, parentNode, childNodes) {
    if (!childNodes) return null;
    for (var i = 0, l = childNodes.length; i < l; i++) {
        childNodes[i].name = childNodes[i].name.replace('', '');
    }
    return childNodes;
}

//导出
function export_all() {
    var rows = _all_win_datagrid.selectedRows();
    console.log('导出------------------------->',rows)
    if (rows.length <= 0) {
        $.supper("alert", {title: "操作提示", msg: "请选择数据！"});
        return;
    }
    let wmsMiIds = '';
    for (let idx = 0; idx < rows.length; idx++) {
        wmsMiIds += rows[idx].wmsMiId + ',';
    }
    if (wmsMiIds == '') {
        $.supper("alert", {title: "操作提示", msg: "请选择数据！"});
        return;
    } else {
        wmsMiIds = wmsMiIds.substring(0, wmsMiIds.lastIndexOf(','))
    }
    var vdata = 'wmsMiIds=' + wmsMiIds;
    console.log('wmsMiIds------------------------->',wmsMiIds)
    var newTab = window.open('about:blank');
    $.supper("doservice", {
        "service": "enterWarehouseExportService.exportmMdMateriel", "data": vdata, "BackE": function (jsondata) {
            if (jsondata.code == "1") {
                newTab.location.href = jsondata.obj.path;
            } else
                $.supper("alert", {title: "操作提示", msg: "操作失败！"});
        }
    });
}

//获取全部，上架，未上架数量
function getMdMaterielInfoCount() {
    $.supper("doservice", {
        "service": "mdMaterielInfoService.getMdMaterielInfoCount", "data": '', "BackE": function (jsondata) {
            if (jsondata.code == "1") {
                $('#allCountt').html(jsondata.obj.allCount);
                $('#offShelfCountt').html(jsondata.obj.offShelfCount);
                $('#shelvesCountt').html(jsondata.obj.shelvesCount);
            } else
                $.supper("alert", {title: "操作提示", msg: "系统错误！"});
        }
    });
}

//全部，上架，未上架选项卡
function tabSearch(num) {
    _que_state = '';
    if (num == 1) {
        $('#countt1').removeClass('countboxitem');
        $('#countt2').removeClass('countboxitemon');
        $('#countt3').removeClass('countboxitemon');
        $('#countt1').addClass('countboxitemon');
        $('#countt2').addClass('countboxitem');
        $('#countt3').addClass('countboxitem');
        _que_state = '';
    }
    if (num == 2) {
        $('#countt1').removeClass('countboxitemon');
        $('#countt2').removeClass('countboxitem');
        $('#countt3').removeClass('countboxitemon');
        $('#countt1').addClass('countboxitem');
        $('#countt2').addClass('countboxitemon');
        $('#countt3').addClass('countboxitem');
        _que_state = 1;
    }
    if (num == 3) {
        $('#countt1').removeClass('countboxitemon');
        $('#countt2').removeClass('countboxitemon');
        $('#countt3').removeClass('countboxitem');
        $('#countt1').addClass('countboxitem');
        $('#countt2').addClass('countboxitem');
        $('#countt3').addClass('countboxitemon');
        _que_state = '2,3';
    }
    main_search();
}

// 下架商品
var _off_Shelf_Goods = $("#off_Shelf_Goods");

// 打开下架窗口
function open_Off_Shelf_Goods_Box(wmsMiId) {
    _off_wmsMiIds = wmsMiId + ',';
    layer.open({
        title: '违规下架操作',
        area: '660px',
        type: 1,
        content: _off_Shelf_Goods
    });
}

// 打开批量下架窗口
function open_Off_Shelf_Goods_Box2() {
    var rows = _all_win_datagrid.selectedRows();
    console.log('实际列表---------------->', rows)
    if (rows.length <= 0) {
        $.supper("alert", {title: "操作提示", msg: "请选择数据！"});
        return;
    }
    let wmsMiIds = '';
    for (let idx = 0; idx < rows.length; idx++) {
        if (rows[idx].state != 1) {
            $.supper("alert", {title: "操作提示", msg: "不可再次下架已下架商品！"});
            return;
        } else {
            wmsMiIds += rows[idx].wmsMiId + ',';
        }
    }
    if (wmsMiIds == '') {
        $.supper("alert", {title: "操作提示", msg: "请选择数据！"});
        return;
    }
    _off_wmsMiIds = wmsMiIds;
    layer.open({
        title: '违规下架操作',
        area: '660px',
        type: 1,
        content: _off_Shelf_Goods
    });
}

// 下架  批量下架
function Off_Goods() {

    var _off_reason = $("#off_reason").val();
    if (_off_reason == '') {
        $.supper("alert", {title: "操作提示", msg: "下架原因不可为空！"});
        return;
    }
    var vdata = "wmsmiIds=" + _off_wmsMiIds + "&matRemovalReasons=" + _off_reason;
    $.supper("doservice", {
        "service": "mdMaterielInfoService.saveMdMaterielInfo", "data": vdata, "BackE": function (jsondata) {
            if (jsondata.code === 1) {
                $.supper("alert", {title: "操作提示", msg: "下架成功！", BackE: main_search});
                layer.closeAll();
                $("#off_reason").val('');
            } else {
                $.supper("alert", {title: "操作提示", msg: "提交失败！"});
            }
        }
    });
}


//获取首字母 开始
//函数使用,本表收录的字符的Unicode编码范围为19968至40869, XDesigner 整理
var strChineseFirstPY = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY";
//此处收录了375个多音字,数据来自于http://www.51window.net/page/pinyin
var oMultiDiff = {
    "19969": "DZ",
    "19975": "WM",
    "19988": "QJ",
    "20048": "YL",
    "20056": "SC",
    "20060": "NM",
    "20094": "QG",
    "20127": "QJ",
    "20167": "QC",
    "20193": "YG",
    "20250": "KH",
    "20256": "ZC",
    "20282": "SC",
    "20285": "QJG",
    "20291": "TD",
    "20314": "YD",
    "20340": "NE",
    "20375": "TD",
    "20389": "YJ",
    "20391": "CZ",
    "20415": "PB",
    "20446": "YS",
    "20447": "SQ",
    "20504": "TC",
    "20608": "KG",
    "20854": "QJ",
    "20857": "ZC",
    "20911": "PF",
    "20504": "TC",
    "20608": "KG",
    "20854": "QJ",
    "20857": "ZC",
    "20911": "PF",
    "20985": "AW",
    "21032": "PB",
    "21048": "XQ",
    "21049": "SC",
    "21089": "YS",
    "21119": "JC",
    "21242": "SB",
    "21273": "SC",
    "21305": "YP",
    "21306": "QO",
    "21330": "ZC",
    "21333": "SDC",
    "21345": "QK",
    "21378": "CA",
    "21397": "SC",
    "21414": "XS",
    "21442": "SC",
    "21477": "JG",
    "21480": "TD",
    "21484": "ZS",
    "21494": "YX",
    "21505": "YX",
    "21512": "HG",
    "21523": "XH",
    "21537": "PB",
    "21542": "PF",
    "21549": "KH",
    "21571": "E",
    "21574": "DA",
    "21588": "TD",
    "21589": "O",
    "21618": "ZC",
    "21621": "KHA",
    "21632": "ZJ",
    "21654": "KG",
    "21679": "LKG",
    "21683": "KH",
    "21710": "A",
    "21719": "YH",
    "21734": "WOE",
    "21769": "A",
    "21780": "WN",
    "21804": "XH",
    "21834": "A",
    "21899": "ZD",
    "21903": "RN",
    "21908": "WO",
    "21939": "ZC",
    "21956": "SA",
    "21964": "YA",
    "21970": "TD",
    "22003": "A",
    "22031": "JG",
    "22040": "XS",
    "22060": "ZC",
    "22066": "ZC",
    "22079": "MH",
    "22129": "XJ",
    "22179": "XA",
    "22237": "NJ",
    "22244": "TD",
    "22280": "JQ",
    "22300": "YH",
    "22313": "XW",
    "22331": "YQ",
    "22343": "YJ",
    "22351": "PH",
    "22395": "DC",
    "22412": "TD",
    "22484": "PB",
    "22500": "PB",
    "22534": "ZD",
    "22549": "DH",
    "22561": "PB",
    "22612": "TD",
    "22771": "KQ",
    "22831": "HB",
    "22841": "JG",
    "22855": "QJ",
    "22865": "XQ",
    "23013": "ML",
    "23081": "WM",
    "23487": "SX",
    "23558": "QJ",
    "23561": "YW",
    "23586": "YW",
    "23614": "YW",
    "23615": "SN",
    "23631": "PB",
    "23646": "ZS",
    "23663": "ZT",
    "23673": "YG",
    "23762": "TD",
    "23769": "ZS",
    "23780": "QJ",
    "23884": "QK",
    "24055": "XH",
    "24113": "DC",
    "24162": "ZC",
    "24191": "GA",
    "24273": "QJ",
    "24324": "NL",
    "24377": "TD",
    "24378": "QJ",
    "24439": "PF",
    "24554": "ZS",
    "24683": "TD",
    "24694": "WE",
    "24733": "LK",
    "24925": "TN",
    "25094": "ZG",
    "25100": "XQ",
    "25103": "XH",
    "25153": "PB",
    "25170": "PB",
    "25179": "KG",
    "25203": "PB",
    "25240": "ZS",
    "25282": "FB",
    "25303": "NA",
    "25324": "KG",
    "25341": "ZY",
    "25373": "WZ",
    "25375": "XJ",
    "25384": "A",
    "25457": "A",
    "25528": "SD",
    "25530": "SC",
    "25552": "TD",
    "25774": "ZC",
    "25874": "ZC",
    "26044": "YW",
    "26080": "WM",
    "26292": "PB",
    "26333": "PB",
    "26355": "ZY",
    "26366": "CZ",
    "26397": "ZC",
    "26399": "QJ",
    "26415": "ZS",
    "26451": "SB",
    "26526": "ZC",
    "26552": "JG",
    "26561": "TD",
    "26588": "JG",
    "26597": "CZ",
    "26629": "ZS",
    "26638": "YL",
    "26646": "XQ",
    "26653": "KG",
    "26657": "XJ",
    "26727": "HG",
    "26894": "ZC",
    "26937": "ZS",
    "26946": "ZC",
    "26999": "KJ",
    "27099": "KJ",
    "27449": "YQ",
    "27481": "XS",
    "27542": "ZS",
    "27663": "ZS",
    "27748": "TS",
    "27784": "SC",
    "27788": "ZD",
    "27795": "TD",
    "27812": "O",
    "27850": "PB",
    "27852": "MB",
    "27895": "SL",
    "27898": "PL",
    "27973": "QJ",
    "27981": "KH",
    "27986": "HX",
    "27994": "XJ",
    "28044": "YC",
    "28065": "WG",
    "28177": "SM",
    "28267": "QJ",
    "28291": "KH",
    "28337": "ZQ",
    "28463": "TL",
    "28548": "DC",
    "28601": "TD",
    "28689": "PB",
    "28805": "JG",
    "28820": "QG",
    "28846": "PB",
    "28952": "TD",
    "28975": "ZC",
    "29100": "A",
    "29325": "QJ",
    "29575": "SL",
    "29602": "FB",
    "30010": "TD",
    "30044": "CX",
    "30058": "PF",
    "30091": "YSP",
    "30111": "YN",
    "30229": "XJ",
    "30427": "SC",
    "30465": "SX",
    "30631": "YQ",
    "30655": "QJ",
    "30684": "QJG",
    "30707": "SD",
    "30729": "XH",
    "30796": "LG",
    "30917": "PB",
    "31074": "NM",
    "31085": "JZ",
    "31109": "SC",
    "31181": "ZC",
    "31192": "MLB",
    "31293": "JQ",
    "31400": "YX",
    "31584": "YJ",
    "31896": "ZN",
    "31909": "ZY",
    "31995": "XJ",
    "32321": "PF",
    "32327": "ZY",
    "32418": "HG",
    "32420": "XQ",
    "32421": "HG",
    "32438": "LG",
    "32473": "GJ",
    "32488": "TD",
    "32521": "QJ",
    "32527": "PB",
    "32562": "ZSQ",
    "32564": "JZ",
    "32735": "ZD",
    "32793": "PB",
    "33071": "PF",
    "33098": "XL",
    "33100": "YA",
    "33152": "PB",
    "33261": "CX",
    "33324": "BP",
    "33333": "TD",
    "33406": "YA",
    "33426": "WM",
    "33432": "PB",
    "33445": "JG",
    "33486": "ZN",
    "33493": "TS",
    "33507": "QJ",
    "33540": "QJ",
    "33544": "ZC",
    "33564": "XQ",
    "33617": "YT",
    "33632": "QJ",
    "33636": "XH",
    "33637": "YX",
    "33694": "WG",
    "33705": "PF",
    "33728": "YW",
    "33882": "SR",
    "34067": "WM",
    "34074": "YW",
    "34121": "QJ",
    "34255": "ZC",
    "34259": "XL",
    "34425": "JH",
    "34430": "XH",
    "34485": "KH",
    "34503": "YS",
    "34532": "HG",
    "34552": "XS",
    "34558": "YE",
    "34593": "ZL",
    "34660": "YQ",
    "34892": "XH",
    "34928": "SC",
    "34999": "QJ",
    "35048": "PB",
    "35059": "SC",
    "35098": "ZC",
    "35203": "TQ",
    "35265": "JX",
    "35299": "JX",
    "35782": "SZ",
    "35828": "YS",
    "35830": "E",
    "35843": "TD",
    "35895": "YG",
    "35977": "MH",
    "36158": "JG",
    "36228": "QJ",
    "36426": "XQ",
    "36466": "DC",
    "36710": "JC",
    "36711": "ZYG",
    "36767": "PB",
    "36866": "SK",
    "36951": "YW",
    "37034": "YX",
    "37063": "XH",
    "37218": "ZC",
    "37325": "ZC",
    "38063": "PB",
    "38079": "TD",
    "38085": "QY",
    "38107": "DC",
    "38116": "TD",
    "38123": "YD",
    "38224": "HG",
    "38241": "XTC",
    "38271": "ZC",
    "38415": "YE",
    "38426": "KH",
    "38461": "YD",
    "38463": "AE",
    "38466": "PB",
    "38477": "XJ",
    "38518": "YT",
    "38551": "WK",
    "38585": "ZC",
    "38704": "XS",
    "38739": "LJ",
    "38761": "GJ",
    "38808": "SQ",
    "39048": "JG",
    "39049": "XJ",
    "39052": "HG",
    "39076": "CZ",
    "39271": "XT",
    "39534": "TD",
    "39552": "TD",
    "39584": "PB",
    "39647": "SB",
    "39730": "LG",
    "39748": "TPB",
    "40109": "ZQ",
    "40479": "ND",
    "40516": "HG",
    "40536": "HG",
    "40583": "QJ",
    "40765": "YQ",
    "40784": "QJ",
    "40840": "YK",
    "40863": "QJG"
};

//参数,中文字符串
//返回值:拼音首字母串数组
function getPy(str) {
    if (typeof (str) != "string") {
        throw new Error(-1, "函数getPy需要字符串类型参数!");
    }
    var arrResult = new Array(); //保存中间结果的数组
    for (var i = 0, len = str.length; i < len; i++) {
        //获得unicode码
        var ch = str.charAt(i);
        //检查该unicode码是否在处理范围之内,在则返回该码对映汉字的拼音首字母,不在则调用其它函数处理
        arrResult.push(checkCh(ch));
    }
    //处理arrResult,返回所有可能的拼音首字母串数组
    return mkRslt(arrResult);
}

function checkCh(ch) {
    var uni = ch.charCodeAt(0);
    //如果不在汉字处理范围之内,返回原字符,也可以调用自己的处理函数
    if (uni > 40869 || uni < 19968) {
        return ch;
    }
    //dealWithOthers(ch);
    //检查是否是多音字,是按多音字处理,不是就直接在strChineseFirstPY字符串中找对应的首字母
    return (oMultiDiff[uni] ? oMultiDiff[uni] : (strChineseFirstPY.charAt(uni - 19968)));
}

function mkRslt(arr) {
    var arrRslt = [""];
    for (var i = 0, len = arr.length; i < len; i++) {
        var str = arr[i];
        var strlen = str.length;
        if (strlen == 1) {
            for (var k = 0; k < arrRslt.length; k++) {
                arrRslt[k] += str;
            }
        } else {
            var tmpArr = arrRslt.slice(0);
            arrRslt = [];
            for (k = 0; k < strlen; k++) {
                //复制一个相同的arrRslt
                var tmp = tmpArr.slice(0);
                //把当前字符str[k]添加到每个元素末尾
                for (var j = 0; j < tmp.length; j++) {
                    tmp[j] += str.charAt(k);
                }
                //把复制并修改后的数组连接到arrRslt上
                arrRslt = arrRslt.concat(tmp);
            }
        }
    }
    return arrRslt;
}

//获取首字母 结束
//按字母排序 开始
function dogetSortData(data) {
    //  处理数据按字母排序分类。
    let letter_reg = /^[A-Z]$/;
    let list = [];
    let letter = '';
    for (let i = 0; i < data.length; i++) {
        // 添加 # 分组，用来 存放 首字母不能 转为 大写英文的 数据
        list['#'] = [];
        // 首字母 转 大写英文
        letter = (data[i].zimu).slice(0, 1).toUpperCase();
        // 是否 大写 英文 字母
        if (!letter_reg.test(letter)) {
            letter = '#';
        }
        // 创建 字母 分组
        if (!(letter in list)) {
            list[letter] = [];
        }
        // 字母 分组 添加 数据
        list[letter].push(data[i]);
    }
    // 转换 格式 进行 排序；
    let resault = [];
    for (let key in list) {
        resault.push({
            letter: key,
            list: list[key]
        });
    }
    resault.sort((a, b) => {
        return a.letter.charCodeAt(0) - b.letter.charCodeAt(0);
    });
    // # 号分组 放最后
    let last_arr = resault[0];
    resault.splice(0, 1);
    resault.push(last_arr);

    // 转换 数据 格式
    let json_sort = {}
    for (let i = 0; i < resault.length; i++) {
        json_sort[resault[i].letter] = resault[i].list;
    }
    return resault;
}

//按字母排序 结束
// 品牌弹窗
var _xia_Brand_Box = $("#xia_Brand_Box");

// 打开搜索模块品牌弹窗
function open_Brand_Box() {
    layer.open({
        title: '选择品牌',
        area: '700px',
        type: 1,
        content: _xia_Brand_Box
    });
}

//获取品牌列表
var _brandList;//品牌重组数组
function getBrandList() {
    $.supper("doservice", {
        "service": "mdMaterielInfoService.getBrandList", "data": '', "BackE": function (jsondata) {
            var list = jsondata.items;
            for (let i = 0; i < list.length; i++) {
                list[i].zimu = getPy(list[i].brand)[0];
            }
            _brandList = dogetSortData(list);
            initBrandBox_letter();
            searchBrand();
        }
    });
}

//品牌上方字母罗列
function initBrandBox_letter() {
    let str = '';
    str += '<a onclick="searchBrand()">全部品牌</a>';
    for (var i in _brandList) {

        if (_brandList[i].list.length > 0) {
            if (i == _brandList.length - 1) {
                str += '<a onclick="searchBrand(\'' + _brandList[i].letter + '\')">其他</a>';
            } else {
                str += '<a onclick="searchBrand(\'' + _brandList[i].letter + '\')">' + _brandList[i].letter + '</a>';
            }
        } else {
            str += '';
        }
    }
    $("#brandLetter").html(str);
}

//取消选择
function cancel_searchBrand() {
    _brandids = [];
    _brandnamearr = [];
    _brandnamestr = '';
    $("#selectBrandNames").html('暂无');
    $("#cancelBrandNamesBtn").html('');
    for (var i = 0; i < _current_brand_list.length; i++) {
        for (var j = 0; j < _current_brand_list[i].list.length; j++) {
            $("#bselectItem_" + i + '_' + j).removeClass(' lion');
            $("#bcheckItem_" + i + '_' + j).prop("checked", false);
        }
    }
}

//搜索品牌
var _current_brand_list = [];//当前品牌列表
function searchBrand(zimu) {
    _brandids = [];
    _brandnamearr = [];
    _brandnamestr = '';
    $("#selectBrandNames").html('暂无');
    $("#cancelBrandNamesBtn").html('');
    var searchBrandName = $("#brandSearchName").val();
    var reg = new RegExp(searchBrandName);
    var newList = [];
    let str = '';
    for (var i in _brandList) {
        if (_brandList[i].list.length > 0) {
            for (var j in _brandList[i].list) {
                if (zimu == undefined || zimu == null || zimu == '') {
                    if (reg.test(_brandList[i].list[j].brand)) {
                        newList[i] = _brandList[i]
                    }
                } else {
                    if (_brandList[i].letter == zimu) {
                        if (reg.test(_brandList[i].list[j].brand)) {
                            newList[i] = _brandList[i]
                        } else {
                            newList[i] = _brandList[i]
                        }
                    } else {

                    }
                }
            }
        } else {
            str += '';
        }
    }
    _current_brand_list = newList;
    for (var i in newList) {
        str += '<div class="zimu">' + newList[i].letter + '</div>';
        str += '<div class="blist"><ul>';
        for (var j in newList[i].list) {
            if (searchBrandName != undefined && searchBrandName != null && searchBrandName != '') {
                if (reg.test(newList[i].list[j].brand)) {
                    str += '<li onclick="selectBrand(' + i + ',' + j + ')"  id="bselectItem_' + i + '_' + j + '"><input  id="bcheckItem_' + i + '_' + j + '" onclick="selectBrand(' + i + ',' + j + ')" type="checkbox"><span>' + newList[i].list[j].brand + '</span></li>';
                } else {
                    str += '';
                }
            } else {
                str += '<li onclick="selectBrand(' + i + ',' + j + ')"  id="bselectItem_' + i + '_' + j + '"><input  id="bcheckItem_' + i + '_' + j + '"  onclick="selectBrand(' + i + ',' + j + ')" type="checkbox"><span>' + newList[i].list[j].brand + '</span></li>';
            }
        }
        str += '</ul></div><div class="clear"></div>';
    }
    $("#brandLlistitem").html(str);
}

var _brandids = [];//品牌选中的字母和名字的ID数组
var _brandnamearr = [];//选中品牌名字数组
var _brandnamestr;//选中品牌名字拼接
function selectBrand(ii, jj) {
    if (_brandids.length == 0) {
        _brandids[0] = {
            ii: ii,
            jj: jj
        };
        var branddd = _current_brand_list[ii].list[jj].brand;
        _brandnamearr.push(branddd);
        _brandnamestr = branddd + ',';
        $("#bselectItem_" + ii + '_' + jj).addClass(' lion');
        $("#bcheckItem_" + ii + '_' + jj).prop("checked", true);
    } else {
        var bstate = false;
        var aaa = []
        aaa[0] = {
            ii: ii,
            jj: jj
        };
        for (var i = 0; i < _brandids.length; i++) {
            if (_brandids[i].ii == ii && _brandids[i].jj == jj) {
                _brandids.splice(i, 1);
                _brandnamearr.splice(i, 1);
                bstate = false;
            } else {
                bstate = true;
            }
        }
        if (bstate == true) {
            $("#bselectItem_" + ii + '_' + jj).addClass(' lion');
            $("#bcheckItem_" + ii + '_' + jj).prop("checked", true);
            _brandids = _brandids.concat(aaa);
            _brandnamearr = _brandnamearr.concat(_current_brand_list[ii].list[jj].brand);
        } else {
            $("#bselectItem_" + ii + '_' + jj).removeClass(' lion');
            $("#bcheckItem_" + ii + '_' + jj).prop("checked", false);
        }
    }
    _brandnamestr = _brandnamearr.join(',');
    if (_brandnamestr == '') {
        $("#cancelBrandNamesBtn").html('');
        $("#selectBrandNames").html('暂无');
    } else {
        $("#cancelBrandNamesBtn").html('取消选择');
        $("#selectBrandNames").html(_brandnamestr);
    }
}

//品牌窗口确定按钮
function do_Select_Brand() {
    _que_brand = _brandnamestr;
    if (_que_brand != undefined && _que_brand != null && _que_brand != '') {
        $("#brand").html(_que_brand);
    } else {
        $("#brand").html('请选择品牌');
    }
    layer.closeAll();
}


// 商家名称弹窗
var _xia_ApplicantName_Box = $("#xia_ApplicantName_Box");

// 打开搜索模块商家名称弹窗
function open_ApplicantName_Box() {
    layer.open({
        title: '选择商家',
        area: '700px',
        type: 1,
        content: _xia_ApplicantName_Box
    });
}

//获取商家列表
var _applicantNameList;//商家重组数组
function getApplicantNameList() {
    $.supper("doservice", {
        "service": "mdMaterielInfoService.getApplicantNameList", "data": '', "BackE": function (jsondata) {
            var list = jsondata.items;
            for (let i = 0; i < list.length; i++) {
                list[i].zimu = getPy(list[i].applicantName)[0];
            }
            _applicantNameList = dogetSortData(list);
            initApplicantNameBox_letter();
            searchApplicantName();
        }
    });
}

//商家上方字母罗列
function initApplicantNameBox_letter() {
    let str = '';
    str += '<a onclick="searchApplicantName()">全部商家</a>';
    for (var i in _applicantNameList) {

        if (_applicantNameList[i].list.length > 0) {
            if (i == _applicantNameList.length - 1) {
                str += '<a onclick="searchApplicantName(\'' + _applicantNameList[i].letter + '\')">其他</a>';
            } else {
                str += '<a onclick="searchApplicantName(\'' + _applicantNameList[i].letter + '\')">' + _applicantNameList[i].letter + '</a>';
            }
        } else {
            str += '';
        }
    }
    $("#applicantNameLetter").html(str);
}

//商家取消选择
function cancel_searchApplicantName() {
    _applicantnameids = [];
    _applicantnamearr = [];
    _applicantnamestr = '';
    $("#selectApplicantNames").html('暂无');
    $("#cancelApplicantNameBtn").html('');
    for (var i = 0; i < _current_applicantname_list.length; i++) {
        for (var j = 0; j < _current_applicantname_list[i].list.length; j++) {
            $("#aselectItem_" + i + '_' + j).removeClass(' lion');
            $("#acheckItem_" + i + '_' + j).prop("checked", false);
        }
    }
}

//搜索商家
var _current_applicantname_list = [];//当前品牌列表
function searchApplicantName(zimu) {
    _applicantnameids = [];
    _applicantnamearr = [];
    _applicantnamestr = '';
    $("#selectApplicantNames").html('暂无');
    $("#cancelApplicantNameBtn").html('');
    var searchApplicantName = $("#applicantnameSearchName").val();
    var reg = new RegExp(searchApplicantName);
    var newList = [];
    let str = '';
    for (var i in _applicantNameList) {
        if (_applicantNameList[i].list.length > 0) {
            for (var j in _applicantNameList[i].list) {
                if (zimu == undefined || zimu == null || zimu == '') {
                    if (reg.test(_applicantNameList[i].list[j].applicantName)) {
                        newList[i] = _applicantNameList[i]
                    }
                } else {
                    if (_applicantNameList[i].letter == zimu) {
                        if (reg.test(_applicantNameList[i].list[j].applicantName)) {
                            newList[i] = _applicantNameList[i]
                        } else {
                            newList[i] = _applicantNameList[i]
                        }
                    } else {

                    }
                }
            }
        } else {
            str += '';
        }
    }
    _current_applicantname_list = newList;
    for (var i in newList) {
        str += '<div class="zimu">' + newList[i].letter + '</div>';
        str += '<div class="blist"><ul>';
        for (var j in newList[i].list) {
            if (searchApplicantName != undefined && searchApplicantName != null && searchApplicantName != '') {
                if (reg.test(newList[i].list[j].applicantName)) {
                    str += '<li onclick="selectApplicantName(' + i + ',' + j + ')"  id="aselectItem_' + i + '_' + j + '"><input  id="acheckItem_' + i + '_' + j + '" onclick="selectApplicantName(' + i + ',' + j + ')" type="checkbox"><span>' + newList[i].list[j].applicantName + '</span></li>';
                } else {
                    str += '';
                }
            } else {
                str += '<li onclick="selectApplicantName(' + i + ',' + j + ')"  id="aselectItem_' + i + '_' + j + '"><input  id="acheckItem_' + i + '_' + j + '"  onclick="selectApplicantName(' + i + ',' + j + ')" type="checkbox"><span>' + newList[i].list[j].applicantName + '</span></li>';
            }
        }
        str += '</ul></div><div class="clear"></div>';
    }
    $("#applicantnameLlistitem").html(str);
}

var _applicantnameids = [];//品牌选中的字母和名字的ID数组
var _applicantnamearr = [];//选中品牌名字数组
var _applicantnamestr;//选中品牌名字拼接
function selectApplicantName(ii, jj) {
    if (_applicantnameids.length == 0) {
        _applicantnameids[0] = {
            ii: ii,
            jj: jj
        };
        var branddd = _current_applicantname_list[ii].list[jj].applicantName;
        _applicantnamearr.push(branddd);
        _applicantnamestr = branddd + ',';
        $("#aselectItem_" + ii + '_' + jj).addClass(' lion');
        $("#acheckItem_" + ii + '_' + jj).prop("checked", true);
    } else {
        var bstate = false;
        var aaa = []
        aaa[0] = {
            ii: ii,
            jj: jj
        };
        for (var i = 0; i < _applicantnameids.length; i++) {
            if (_applicantnameids[i].ii == ii && _applicantnameids[i].jj == jj) {
                _applicantnameids.splice(i, 1);
                _applicantnamestr.splice(i, 1);
                bstate = false;
            } else {
                bstate = true;
            }
        }
        if (bstate == true) {
            $("#aselectItem_" + ii + '_' + jj).addClass(' lion');
            $("#acheckItem_" + ii + '_' + jj).prop("checked", true);
            _applicantnameids = _applicantnameids.concat(aaa);
            _applicantnamearr = _applicantnamearr.concat(_current_applicantname_list[ii].list[jj].applicantName);
        } else {
            $("#aselectItem_" + ii + '_' + jj).removeClass(' lion');
            $("#acheckItem_" + ii + '_' + jj).prop("checked", false);
        }
    }
    _applicantnamestr = _applicantnamearr.join(',');
    if (_applicantnamestr == '') {
        $("#cancelApplicantNameBtn").html('');
        $("#selectApplicantNames").html('暂无');
    } else {
        $("#cancelApplicantNameBtn").html('取消选择');
        $("#selectApplicantNames").html(_applicantnamestr);
    }
}

//商家窗口确定按钮
function do_Select_ApplicantName() {
    _que_applicantname = _applicantnamestr;
    if (_que_applicantname != undefined && _que_applicantname != null && _que_applicantname != '') {
        $("#applicantName").html(_que_applicantname);
    } else {
        $("#applicantName").html('商家名称');
    }
    layer.closeAll();
}

// 关闭窗口
function close_All_Box() {
    if (_que_brand != undefined && _que_brand != null && _que_brand != '') {
        $("#brand").html(_que_brand);
    } else {
        $("#brand").html('请选择品牌');
    }
    if (_que_applicantname != undefined && _que_applicantname != null && _que_applicantname != '') {
        $("#applicantName").html(_que_applicantname);
    } else {
        $("#applicantName").html('商家名称');
    }
    layer.closeAll();
}